"""renamed provider to payment_provider and customer_phone to customer_phone_number

Revision ID: 210cf228545a
Revises: f5d5592803a6
Create Date: 2026-07-07 01:52:53.952927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210cf228545a'
down_revision: Union[str, Sequence[str], None] = 'f5d5592803a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_provider', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('customer_phone_number', sa.String(length=20), nullable=True))
    op.drop_column('transactions', 'customer_phone')
    op.drop_column('transactions', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'customer_phone_number')
    op.drop_column('transactions', 'payment_provider')
    # ### end Alembic commands ###
